import { Barlow, Fraunces } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Image from "next/image";
import IconDown from '/public/images/icon-arrow-down.svg';
import Footer from "./components/footer";

const barlow = Barlow({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });
const fraunces = Fraunces({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "sunnyside",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fraunces.className} w-full flex flex-col items-center justify-center`}>
        <header id="header" className="h-[900px] p-10 w-full items-center flex flex-col">
            <Navbar />
            <div className="text-5xl mt-40 flex flex-col items-center text-center font-bold tracking-wider text-white leading-snug">
              <h1 className="mb-16">WE ARE CREATIVES</h1>
              <Image src={IconDown} alt='icon down' width={50} />
            </div>
        </header>  
        {children}
        <Footer />
      </body>
    </html>
  );
}
